### ISSUE TITLE
Support for Koa v2.x

### ISSUE THREAD

**Issue by SokolskyNikita** [koajs/basic-auth#10]
I was wondering if anyone is working on migrating this middleware to Koa v.2.x?

If not, can I do an implementation in the upcoming week? Thank you.

**Comment by coderhaoxin** [comment]
PR welcome!

**Comment by focused** [comment]
+1

**Comment by coderhaoxin** [comment]
https://github.com/koajs/basic-auth/tree/next

```
npm i koa-basic-auth@next
```
